### ISSUE TITLE
Posting Posts

### ISSUE THREAD

**Issue by wrathbun** [COSC481W-2022Winter/capstone-team-mercury-cosc481w-2022#5]
As a user of Cutestpaw, I would like to be able to post content so that I
may share it with friends, followers, and other users in general

Constraints:
1. Only logged in users will have access to this page
2. Only text posts for now

Acceptance Criteria:
1. Error message upon trying to post an empty post
2. After Submitting a new post, the post will be added to the database
3. After submitting a post the user will be sent to the content feed
4. Each post should have an author

Tasks: 
1. Frontend new post page (Olga)
   1.1. Form with fields for text and images (placeholder)
   1.2. Error message when needed
   1.3. Pass post information to the backend
   1.4. Redirect to the content feed when a post is successfully uploaded
2. Backend API (Willam)
   2.1. addPost API on the backend to add a post to the database
3. Database (William)
   3.1 New table for posts (id, postedBy, content, attachments)

**Comment by sjiang1** [comment]
Add one acceptance criterion:
4. Post information should include the author

**Comment by wrathbun** [comment]
Didn't receive any work or notification from olga, closed with #17
